//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTransfer.i18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileTransfer.i18n.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The pprogram already startup! 的本地化字符串。
        /// </summary>
        internal static string AlreadyStartupTip {
            get {
                return ResourceManager.GetString("AlreadyStartupTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Failed... 的本地化字符串。
        /// </summary>
        internal static string CheckFailedStr {
            get {
                return ResourceManager.GetString("CheckFailedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Success... 的本地化字符串。
        /// </summary>
        internal static string CheckSuccessStr {
            get {
                return ResourceManager.GetString("CheckSuccessStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommandDescription 的本地化字符串。
        /// </summary>
        internal static string CommandDescriptionTitle {
            get {
                return ResourceManager.GetString("CommandDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        internal static string CommandHeaderTitle {
            get {
                return ResourceManager.GetString("CommandHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommandUsage 的本地化字符串。
        /// </summary>
        internal static string CommandUsageTitle {
            get {
                return ResourceManager.GetString("CommandUsageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Failed... 的本地化字符串。
        /// </summary>
        internal static string ConnectFailedStr {
            get {
                return ResourceManager.GetString("ConnectFailedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Success... 的本地化字符串。
        /// </summary>
        internal static string ConnectSuccessStr {
            get {
                return ResourceManager.GetString("ConnectSuccessStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection down... 的本地化字符串。
        /// </summary>
        internal static string DisconnectedStr {
            get {
                return ResourceManager.GetString("DisconnectedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Impending disconnection... 的本地化字符串。
        /// </summary>
        internal static string DisConnectStr {
            get {
                return ResourceManager.GetString("DisConnectStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit the program 的本地化字符串。
        /// </summary>
        internal static string ExitHelp {
            get {
                return ResourceManager.GetString("ExitHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To clear the console 的本地化字符串。
        /// </summary>
        internal static string HelpCls {
            get {
                return ResourceManager.GetString("HelpCls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get command help 的本地化字符串。
        /// </summary>
        internal static string HelpHelp {
            get {
                return ResourceManager.GetString("HelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter &quot;help&quot; to get help doc 的本地化字符串。
        /// </summary>
        internal static string HelpTip {
            get {
                return ResourceManager.GetString("HelpTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input an option: 的本地化字符串。
        /// </summary>
        internal static string InputTip {
            get {
                return ResourceManager.GetString("InputTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set language like Chinese:&apos;zh-cn&apos;,English:&apos;en-us&apos;... 的本地化字符串。
        /// </summary>
        internal static string LangHelp {
            get {
                return ResourceManager.GetString("LangHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive: 的本地化字符串。
        /// </summary>
        internal static string ReceiveStr {
            get {
                return ResourceManager.GetString("ReceiveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to restart the application to apply changes? 的本地化字符串。
        /// </summary>
        internal static string RestartAsk {
            get {
                return ResourceManager.GetString("RestartAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send: 的本地化字符串。
        /// </summary>
        internal static string SendStr {
            get {
                return ResourceManager.GetString("SendStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get server list or connect to  the specified IP 的本地化字符串。
        /// </summary>
        internal static string ServerHelp {
            get {
                return ResourceManager.GetString("ServerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying to connect to the server... 的本地化字符串。
        /// </summary>
        internal static string TryConnectStr {
            get {
                return ResourceManager.GetString("TryConnectStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unkwon command 的本地化字符串。
        /// </summary>
        internal static string UnkwonHelp {
            get {
                return ResourceManager.GetString("UnkwonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome o the FileTransfer app! 的本地化字符串。
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
